//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buildingTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class buildingInfoData
    {
        public int buildingID { get; set; }
        public string buildingNumber { get; set; }
        public string buildingNameArabic { get; set; }
        public string buildingNameEnglish { get; set; }
        public System.DateTime createDate { get; set; }
        public string constructionContractorCompany { get; set; }
        public string buildingImage { get; set; }
        public Nullable<int> buildingType_FK { get; set; }
        public Nullable<int> buildingUses_FK { get; set; }
        public Nullable<int> construction_FK { get; set; }
        public Nullable<int> zone_FK { get; set; }
        public double buildingWidth { get; set; }
        public double buildingHeight { get; set; }
        public double buildingLength { get; set; }
        public double totalBuilding { get; set; }
        public int postNumber { get; set; }
        public string instrumentNumber { get; set; }
    
        public virtual buildingTypeData buildingTypeData { get; set; }
        public virtual buildingUsesData buildingUsesData { get; set; }
        public virtual constructionData constructionData { get; set; }
        public virtual zoneData zoneData { get; set; }
    }
}
