//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buildingTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildingUsesData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buildingUsesData()
        {
            this.buildingInfoDatas = new HashSet<buildingInfoData>();
        }
    
        public int buildingUsesID { get; set; }
        public string buildingUsesName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buildingInfoData> buildingInfoDatas { get; set; }
    }
}
