//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buildingTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bulding_TaskEntities : DbContext
    {
        public Bulding_TaskEntities()
            : base("name=Bulding_TaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingInfoData> buildingInfoDatas { get; set; }
        public virtual DbSet<buildingTypeData> buildingTypeDatas { get; set; }
        public virtual DbSet<buildingUsesData> buildingUsesDatas { get; set; }
        public virtual DbSet<constructionData> constructionDatas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<zoneData> zoneDatas { get; set; }
    }
}
